from __future__ import annotations


COMPANY_NAMES = {
    "MSFT": "Microsoft Corporation",
    "ORCL": "Oracle Corporation",
    "GOOG": "Alphabet Inc.",
    "AVGO": "Broadcom Inc.",
    "SNDK": "Sandisk Corporation",
    "NVDA": "NVIDIA Corporation",
    "MRVL": "Marvell Technology, Inc.",
    "AAPL": "Apple Inc.",
    "AMZN": "Amazon.com, Inc.",
    "META": "Meta Platforms, Inc.",
    "LITE": "Lumentum Holdings Inc.",
    "AMAT": "Applied Materials, Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Company Limited",
    "ASML": "ASML Holding N.V.",
    "AMD": "Advanced Micro Devices, Inc.",
}


CIKS = {
    "MSFT": "0000789019",
    "ORCL": "0001341439",
    "GOOG": "0001652044",
    "AVGO": "0001730168",
    "SNDK": "0002023554",
    "NVDA": "0001045810",
    "MRVL": "0001835632",
    "AAPL": "0000320193",
    "AMZN": "0001018724",
    "META": "0001326801",
    "LITE": "0001633978",
    "AMAT": "0000006951",
    "TSM": "0001046179",
    "ASML": "0000937966",
    "AMD": "0000002488",
}


def sec_filings_url(ticker: str, form: str) -> str:
    cik = CIKS[ticker]
    return f"https://www.sec.gov/edgar/browse/?CIK={cik}&owner=exclude&action=getcompany&type={form}"


TARGET_PRICE_SNAPSHOTS = {
    "MSFT": {
        "as_of": "2026-08-12",
        "source_url": "https://price-target.com/ai/microsoft/",
        "street": [
            {"firm": "Wells Fargo", "target": 700.0, "date": "2026-08-12"},
            {"firm": "Bernstein", "target": 660.0, "date": "2026-08-10"},
            {"firm": "Citi", "target": 600.0, "date": "2026-07-30"},
            {"firm": "UBS", "target": 525.0, "date": "2026-07-30"},
        ],
        "house": {"Bear": 450.0, "Base": 550.0, "Bull": 660.0},
        "basis": "A transparent range centered on the recent institutional cluster, with dispersion driven by Azure and AI monetization versus infrastructure-return risk.",
    },
    "ORCL": {
        "as_of": "2026-08-21",
        "source_url": "https://stockanalysis.com/stocks/orcl/forecast/",
        "street": [
            {"firm": "J.P. Morgan", "target": 200.0, "date": "2026-08-17"},
            {"firm": "RBC Capital", "target": 190.0, "date": "2026-08-12"},
            {"firm": "UBS", "target": 245.0, "date": "2026-08-06"},
        ],
        "house": {"Bear": 170.0, "Base": 245.0, "Bull": 320.0},
        "basis": "The range weighs OCI backlog conversion against capex, financing and deployment-timing risk; it is not a consensus average.",
    },
    "GOOG": {
        "as_of": "2026-08-24",
        "source_url": "https://stockanalysis.com/stocks/googl/forecast/",
        "street": [
            {"firm": "Citizens JMP", "target": 515.0, "date": "2026-08-24"},
            {"firm": "Bernstein", "target": 385.0, "date": "2026-08-20"},
            {"firm": "Evercore ISI", "target": 420.0, "date": "2026-07-23"},
            {"firm": "UBS", "target": 379.0, "date": "2026-07-23"},
        ],
        "house": {"Bear": 360.0, "Base": 430.0, "Bull": 515.0},
        "basis": "The range balances Search durability and Cloud acceleration against higher AI capex and the monetization gap between AI usage and advertising economics.",
    },
    "AVGO": {
        "as_of": "2026-08-21",
        "source_url": "https://stockanalysis.com/stocks/avgo/forecast/",
        "street": [
            {"firm": "Mizuho", "target": 530.0, "date": "2026-08-21"},
            {"firm": "Bank of America", "target": 530.0, "date": "2026-08-20"},
            {"firm": "Bernstein", "target": 550.0, "date": "2026-08-20"},
            {"firm": "BMO Capital", "target": 455.0, "date": "2026-08-20"},
        ],
        "house": {"Bear": 430.0, "Base": 525.0, "Bull": 590.0},
        "basis": "The range separates custom-accelerator and networking growth from customer concentration, ASIC margin pressure and software-integration risk.",
    },
    "SNDK": {
        "as_of": "2026-08-25",
        "source_url": "https://stockanalysis.com/stocks/sndk/forecast/",
        "street": [
            {"firm": "Mizuho", "target": 1875.0, "date": "2026-08-25"},
            {"firm": "Bernstein", "target": 3000.0, "date": "2026-08-17"},
            {"firm": "Goldman Sachs", "target": 2200.0, "date": "2026-08-14"},
            {"firm": "Wedbush", "target": 2000.0, "date": "2026-08-14"},
        ],
        "house": {"Bear": 1600.0, "Base": 2150.0, "Bull": 2900.0},
        "basis": "The range reflects NAND pricing and enterprise-SSD mix while keeping cycle normalization, supply response and customer concentration explicit.",
    },
    "NVDA": {
        "as_of": "2026-08-25",
        "source_url": "https://stockanalysis.com/stocks/nvda/forecast/",
        "street": [
            {"firm": "Raymond James", "target": 352.0, "date": "2026-08-25"},
            {"firm": "KeyBanc", "target": 330.0, "date": "2026-08-24"},
            {"firm": "Morgan Stanley", "target": 288.0, "date": "2026-08-14"},
        ],
        "house": {"Bear": 245.0, "Base": 305.0, "Bull": 355.0},
        "basis": "The range weighs Rubin and Blackwell demand visibility against growth deceleration, customer silicon substitution and multiple compression.",
    },
}


MARKET_SHARE_SNAPSHOTS = {
    "MSFT": {
        "title": "Global cloud infrastructure services",
        "period": "Q2 2026",
        "values": {"AWS": 28.0, "Microsoft": 20.0, "Google Cloud": 15.0, "Oracle and tier two": 5.0, "Other": 32.0},
        "source": "Synergy Research Group",
        "source_url": "https://www.srgresearch.com/articles/q2-cloud-market-passes-143-billion-highest-growth-rate-in-eight-years",
        "note": "The named tier-two share is a grouped visual estimate; use the source chart for exact vendor definitions.",
    },
    "ORCL": {
        "title": "Global cloud infrastructure services",
        "period": "Q2 2026",
        "values": {"AWS": 28.0, "Microsoft": 20.0, "Google Cloud": 15.0, "Oracle and tier two": 5.0, "Other": 32.0},
        "source": "Synergy Research Group",
        "source_url": "https://www.srgresearch.com/articles/q2-cloud-market-passes-143-billion-highest-growth-rate-in-eight-years",
        "note": "Oracle is shown inside a grouped tier-two estimate because the public release does not disclose a standalone percentage.",
    },
    "GOOG": {
        "title": "Global cloud infrastructure services",
        "period": "Q2 2026",
        "values": {"AWS": 28.0, "Microsoft": 20.0, "Google Cloud": 15.0, "Oracle and tier two": 5.0, "Other": 32.0},
        "source": "Synergy Research Group",
        "source_url": "https://www.srgresearch.com/articles/q2-cloud-market-passes-143-billion-highest-growth-rate-in-eight-years",
        "note": "Share is based on enterprise cloud infrastructure service revenue, not total company revenue.",
    },
    "AVGO": {
        "title": "AI accelerator vendor revenue",
        "period": "2025 reference view",
        "values": {"NVIDIA": 78.0, "Broadcom": 10.3, "AMD": 7.0, "Other": 4.7},
        "source": "IDC market outlook",
        "source_url": "https://www.semi.org/sites/semi.org/files/2025-09/1%20%EA%B9%80%EC%88%98%EA%B2%B8_IDC%20Semiconductor%20Market%20Outlook.pdf",
        "note": "A reference category view; custom ASIC design share and total accelerator revenue share are not interchangeable.",
    },
    "SNDK": {
        "title": "Global NAND shipments",
        "period": "Q2 2026",
        "values": {"Samsung": 25.0, "SK hynix": 22.0, "YMTC": 14.0, "Kioxia": 14.0, "Micron": 13.0, "SanDisk": 11.0, "Other": 1.0},
        "source": "Counterpoint Research",
        "source_url": "https://counterpointresearch.com/en/insights/server-led-essds-hit-48-percent-of-nand-shipments",
        "note": "Shipment share differs from revenue share because product mix and pricing vary by supplier.",
    },
    "NVDA": {
        "title": "Worldwide discrete data-center GPUs",
        "period": "H1 2024 regulatory reference",
        "values": {"NVIDIA": 85.0, "AMD and other": 15.0},
        "source": "European Commission decision using IDC and company data",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32024M11766",
        "note": "The public decision reports NVIDIA within an 80%-90% range; 85% is the midpoint used only for visualization.",
    },
}


EXTENDED_PROFILES = {
    "GOOG": {
        "business_model": "A global advertising, cloud, subscription and computing-platform business built around Search, YouTube, Android, Google Cloud and AI infrastructure.",
        "research_thesis": "Search and YouTube cash generation can fund a faster-growing cloud and AI platform, while distribution and proprietary data provide multiple monetization paths.",
        "counter_thesis": "AI interfaces can raise serving costs, weaken click economics and require heavy infrastructure spending before new monetization offsets pressure on the core search franchise.",
        "growth_engines": ["Google Cloud and enterprise AI", "Search and commerce monetization", "YouTube subscriptions and advertising"],
        "key_kpis": ["Search revenue growth", "Google Cloud growth and margin", "Capex intensity", "AI query monetization"],
        "key_questions": ["Can AI Mode protect query share without diluting search economics?", "Does Cloud margin scale faster than infrastructure investment?", "How durable is YouTube growth across advertising and subscriptions?"],
        "moat_factors": [("Distribution", "Search, Android, Chrome and YouTube create global consumer reach."), ("Data and intent", "Commercial intent and user behavior strengthen relevance and monetization."), ("Compute stack", "TPUs, models and cloud infrastructure support differentiated economics."), ("Capital capacity", "Core cash generation funds frontier-model and infrastructure investment.")],
        "catalysts": ["Cloud backlog converts with improving margins.", "AI search usage monetizes without a material cost penalty.", "YouTube gains viewing and advertising share.", "Capex growth begins to trail operating-profit growth."],
        "risks": ["AI assistants weaken search distribution or pricing.", "Infrastructure costs and depreciation pressure free cash flow.", "Regulatory remedies change default distribution economics.", "Cloud growth requires lower-margin third-party compute."],
        "monitoring_signals": [("Search", "Query share, commercial query growth and cost per query"), ("Cloud", "Revenue, backlog, margin and capacity"), ("Cash", "Capex, depreciation and free cash flow"), ("Regulation", "Distribution and advertising remedies")],
        "scenario_defaults": {"years": 3, "bear_growth": .10, "base_growth": .16, "bull_growth": .22, "bear_margin": .28, "base_margin": .32, "bull_margin": .36},
        "competitive_dimensions": ["Distribution", "Data", "Cloud scale", "AI stack", "Monetization"],
        "competitive_scores": {"Alphabet": [5, 5, 4, 5, 5], "Microsoft": [5, 4, 5, 5, 5], "Amazon": [4, 4, 5, 4, 5], "Meta": [4, 5, 2, 4, 5]},
        "diligence_questions": ["What is the incremental cost and revenue per AI search interaction?", "How much cloud capacity is committed versus built ahead of demand?", "Which regulatory outcomes would change distribution economics?"],
        "source_url": "https://www.sec.gov/edgar/browse/?CIK=0001652044&owner=exclude&action=getcompany&type=10-K",
    },
    "AVGO": {
        "business_model": "A semiconductor and infrastructure-software platform spanning custom AI accelerators, networking, connectivity and VMware subscription software.",
        "research_thesis": "Custom AI silicon and networking can compound with infrastructure software cash generation, producing a differentiated mix of high growth and recurring revenue.",
        "counter_thesis": "Customer concentration, custom-silicon bargaining power and VMware integration complexity can make headline growth less durable than current expectations imply.",
        "growth_engines": ["Custom AI accelerators", "Data-center networking", "VMware subscription conversion"],
        "key_kpis": ["AI semiconductor revenue", "Customer concentration", "Semiconductor gross margin", "VMware bookings and free cash flow"],
        "key_questions": ["How durable is Broadcom's position as hyperscalers diversify design partners?", "Can AI revenue scale without diluting margin?", "Does VMware retention support the modeled software cash flow?"],
        "moat_factors": [("Co-design", "Deep engineering relationships embed Broadcom in long product roadmaps."), ("Networking", "Switching and connectivity broaden value beyond accelerators."), ("IP portfolio", "Specialized silicon and connectivity IP compress customer time to market."), ("Software cash flow", "Recurring infrastructure software can fund semiconductor investment.")],
        "catalysts": ["Additional hyperscaler programs enter production.", "AI networking grows alongside accelerator shipments.", "VMware bookings stabilize after portfolio changes.", "Free cash flow expands faster than integration costs."],
        "risks": ["A top customer changes design partners.", "Custom silicon pricing compresses gross margin.", "VMware customer attrition exceeds savings.", "Acquisition leverage limits strategic flexibility."],
        "monitoring_signals": [("AI", "Program count, revenue and customer mix"), ("Margins", "Semiconductor gross margin and mix"), ("Software", "Bookings, retention and recurring revenue"), ("Cash", "FCF, debt reduction and integration costs")],
        "scenario_defaults": {"years": 3, "bear_growth": .14, "base_growth": .22, "bull_growth": .30, "bear_margin": .36, "base_margin": .42, "bull_margin": .47},
        "competitive_dimensions": ["Custom silicon", "Networking", "Software", "Customer access", "Cash generation"],
        "competitive_scores": {"Broadcom": [5, 5, 4, 5, 5], "NVIDIA": [4, 5, 3, 5, 5], "Marvell": [4, 4, 2, 4, 3], "AMD": [3, 4, 2, 4, 4]},
        "diligence_questions": ["What share of AI revenue is tied to each major customer?", "How do new programs change gross-margin mix?", "What retention evidence supports VMware cash-flow assumptions?"],
        "source_url": "https://www.sec.gov/edgar/browse/?CIK=0001730168&owner=exclude&action=getcompany&type=10-K",
    },
    "SNDK": {
        "business_model": "A NAND flash and storage company serving data-center, client, mobile and consumer markets through memory products, enterprise SSDs and branded storage.",
        "research_thesis": "AI-driven enterprise SSD demand and constrained NAND supply can improve pricing, utilization and product mix for a focused storage supplier.",
        "counter_thesis": "NAND remains cyclical: high prices can trigger supply, customer inventory corrections or technology transitions that reverse margins quickly.",
        "growth_engines": ["Enterprise SSD demand", "NAND pricing and mix", "Technology-node and yield improvement"],
        "key_kpis": ["NAND ASP", "Enterprise SSD mix", "Bit shipments", "Gross margin and inventory"],
        "key_questions": ["How much of current pricing is contracted versus spot-driven?", "Can enterprise SSD mix remain elevated through a supply response?", "What normalized margin survives the NAND cycle?"],
        "moat_factors": [("Flash IP", "Controller, firmware and NAND integration support performance and qualification."), ("Manufacturing partnership", "Long-standing supply collaboration supports scale and technology access."), ("Qualification", "Enterprise storage qualification can create product-cycle stickiness."), ("Brand and channels", "Consumer and client distribution diversify routes to market.")],
        "catalysts": ["Enterprise SSD mix rises faster than expected.", "Long-term agreements extend price visibility.", "Yield and node transitions lower unit cost.", "Industry capacity stays disciplined."],
        "risks": ["NAND pricing reverses after customer inventory builds.", "Supply additions outpace demand.", "Technology transitions raise cost or delay qualification.", "Customer concentration weakens pricing power."],
        "monitoring_signals": [("Pricing", "Contract and spot NAND prices"), ("Mix", "Enterprise SSD share and customer qualification"), ("Supply", "Industry capex and bit growth"), ("Cash", "Inventory, working capital and FCF")],
        "scenario_defaults": {"years": 3, "bear_growth": .03, "base_growth": .12, "bull_growth": .20, "bear_margin": .18, "base_margin": .28, "bull_margin": .38},
        "competitive_dimensions": ["NAND scale", "Enterprise SSD", "Technology", "Channels", "Cycle resilience"],
        "competitive_scores": {"SanDisk": [4, 4, 4, 5, 3], "Samsung": [5, 5, 5, 5, 5], "SK hynix": [5, 5, 5, 4, 4], "Micron": [4, 4, 5, 4, 4]},
        "diligence_questions": ["What portion of forward demand has enforceable pricing and volume terms?", "How does enterprise SSD mix affect normalized gross margin?", "Which capacity additions can change the 12-month supply balance?"],
        "source_url": "https://www.sec.gov/edgar/browse/?CIK=0002023554&owner=exclude&action=getcompany&type=10-K",
    },
    "NVDA": {
        "business_model": "A full-stack accelerated-computing platform monetized through data-center systems, GPUs, networking, software and ecosystem adoption.",
        "research_thesis": "Architecture leadership, CUDA and system-level integration can sustain premium economics as accelerated computing expands across training, inference and enterprise workloads.",
        "counter_thesis": "Customer concentration, custom silicon and a decelerating infrastructure cycle can pressure growth and valuation even if NVIDIA remains the technical leader.",
        "growth_engines": ["Data-center accelerators", "Networking and systems", "Enterprise inference and software"],
        "key_kpis": ["Data-center revenue", "Gross margin", "Supply and product transitions", "Customer concentration"],
        "key_questions": ["Does Rubin extend performance leadership without a disruptive transition?", "How quickly do custom accelerators take addressable workloads?", "Can software and systems broaden the profit pool beyond GPUs?"],
        "moat_factors": [("CUDA ecosystem", "Developers and optimized libraries reinforce adoption."), ("System architecture", "Compute, networking and software are designed together."), ("Roadmap velocity", "Frequent product cycles raise the execution hurdle for competitors."), ("Scale", "Demand visibility and supplier relationships support rapid deployment.")],
        "catalysts": ["Rubin ramps with strong supply and demand.", "Inference becomes a broader enterprise workload.", "Networking and software outgrow the core GPU cycle.", "Gross margin stabilizes through product transitions."],
        "risks": ["Hyperscalers shift workloads to custom silicon.", "Export controls limit accessible markets.", "Product transitions create supply or margin volatility.", "AI infrastructure returns disappoint end customers."],
        "monitoring_signals": [("Demand", "Cloud capex and customer concentration"), ("Roadmap", "Shipment timing and performance"), ("Margins", "Mix, supply costs and gross margin"), ("Competition", "Custom accelerators and software adoption")],
        "scenario_defaults": {"years": 3, "bear_growth": .12, "base_growth": .22, "bull_growth": .32, "bear_margin": .48, "base_margin": .56, "bull_margin": .62},
        "competitive_dimensions": ["Compute", "Networking", "Software", "Developer ecosystem", "Scale"],
        "competitive_scores": {"NVIDIA": [5, 5, 5, 5, 5], "AMD": [4, 4, 3, 3, 4], "Broadcom": [4, 5, 3, 4, 4], "Hyperscaler silicon": [4, 4, 4, 4, 5]},
        "diligence_questions": ["How concentrated is revenue by customer and platform generation?", "Which inference workloads are most exposed to custom silicon?", "What gross margin is sustainable through the next transition?"],
        "source_url": "https://www.sec.gov/edgar/browse/?CIK=0001045810&owner=exclude&action=getcompany&type=10-K",
    },
}


def _focused_profile(
    *, business_model: str, thesis: str, counter: str, engines: list[str], kpis: list[str],
    questions: list[str], moat: list[tuple[str, str]], catalysts: list[str], risks: list[str],
    monitoring: list[tuple[str, str]], scenario: tuple[float, float, float, float, float, float],
    dimensions: list[str], scores: dict[str, list[int]], diligence: list[str], source_url: str,
) -> dict[str, object]:
    bear_growth, base_growth, bull_growth, bear_margin, base_margin, bull_margin = scenario
    return {
        "business_model": business_model,
        "research_thesis": thesis,
        "counter_thesis": counter,
        "growth_engines": engines,
        "key_kpis": kpis,
        "key_questions": questions,
        "moat_factors": moat,
        "catalysts": catalysts,
        "risks": risks,
        "monitoring_signals": monitoring,
        "scenario_defaults": {"years": 3, "bear_growth": bear_growth, "base_growth": base_growth, "bull_growth": bull_growth, "bear_margin": bear_margin, "base_margin": base_margin, "bull_margin": bull_margin},
        "competitive_dimensions": dimensions,
        "competitive_scores": scores,
        "diligence_questions": diligence,
        "source_url": source_url,
    }


EXTENDED_PROFILES.update({
    "MRVL": _focused_profile(
        business_model="A fabless semiconductor platform focused on data-center connectivity, custom compute, networking, carrier infrastructure and storage silicon.",
        thesis="Custom AI silicon and high-speed interconnect can move Marvell toward faster growth and better mix as hyperscalers redesign data-center architectures.",
        counter="A small number of large programs, long qualification cycles and aggressive competitors make revenue timing and margin progression unusually sensitive to execution.",
        engines=["Custom cloud accelerators", "800G and 1.6T connectivity", "Data-center switching and storage"],
        kpis=["Data-center revenue", "Custom silicon program ramps", "Gross margin", "Customer concentration"],
        questions=["How many custom programs are in volume production?", "Can optical and switching growth offset legacy declines?", "Does custom silicon scale without structurally diluting margin?"],
        moat=[("Co-design", "Long customer roadmaps embed engineering teams in platform decisions."), ("Connectivity IP", "SerDes, switching and electro-optics span multiple data paths."), ("Qualification", "Complex silicon is difficult to replace after validation."), ("Portfolio breadth", "Compute, network and storage products can share customer access.")],
        catalysts=["Additional custom programs reach volume production.", "1.6T optical demand accelerates.", "Legacy end markets recover.", "Operating leverage appears as revenue scales."],
        risks=["A hyperscaler delays or replaces a custom program.", "Custom silicon mix pressures gross margin.", "Networking competition intensifies.", "Inventory corrections obscure end demand."],
        monitoring=[("Programs", "Design wins and production timing"), ("Optics", "800G and 1.6T shipment growth"), ("Margins", "Mix and operating leverage"), ("Customers", "Revenue concentration")],
        scenario=(.08, .18, .28, .08, .18, .25),
        dimensions=["Custom silicon", "Connectivity", "Cloud access", "Software", "Scale"],
        scores={"Marvell": [5, 5, 4, 2, 3], "Broadcom": [5, 5, 5, 4, 5], "NVIDIA": [4, 5, 5, 5, 5], "AMD": [3, 4, 4, 4, 4]},
        diligence=["Separate committed program revenue from pipeline language.", "Reconcile AI growth with customer concentration.", "Track mix effects on gross and operating margin."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0001835632&owner=exclude&action=getcompany&type=10-K",
    ),
    "AAPL": _focused_profile(
        business_model="A global consumer-technology ecosystem monetized through devices, services, payments, software distribution and a tightly integrated silicon and operating-system stack.",
        thesis="The installed base, premium positioning and services attach can sustain cash generation while custom silicon and on-device intelligence support product differentiation.",
        counter="Mature device categories, regulatory pressure on platform economics and dependence on premium replacement cycles can constrain growth despite a durable ecosystem.",
        engines=["Services monetization", "Premium device mix", "Installed-base expansion"],
        kpis=["iPhone revenue", "Services growth and margin", "Installed base", "Gross margin by mix"],
        questions=["Can services grow without regulatory dilution?", "Will on-device AI accelerate replacement demand?", "How much premium pricing can the ecosystem retain?"],
        moat=[("Installed base", "Devices, accounts and subscriptions create recurring touchpoints."), ("Integration", "Silicon, software and hardware are optimized together."), ("Brand", "Trust and premium positioning support pricing power."), ("Distribution", "Retail, carrier and developer channels reinforce reach.")],
        catalysts=["A stronger device replacement cycle.", "Services mix expands margins.", "New form factors create another installed-base layer.", "Capital returns compound per-share value."],
        risks=["App-distribution remedies reduce fees.", "China demand or supply weakens.", "AI features fail to change replacement behavior.", "Premium smartphones lose share."],
        monitoring=[("Devices", "Units, mix and replacement cycle"), ("Services", "Growth, margin and regulation"), ("China", "Demand and supply exposure"), ("Cash", "FCF and capital returns")],
        scenario=(.02, .06, .10, .28, .32, .35),
        dimensions=["Ecosystem", "Brand", "Silicon", "Services", "Distribution"],
        scores={"Apple": [5, 5, 5, 5, 5], "Samsung": [4, 4, 4, 3, 5], "Google": [4, 4, 4, 5, 5], "Microsoft": [4, 4, 4, 5, 5]},
        diligence=["Separate installed-base growth from pricing and mix.", "Quantify regulatory sensitivity in Services.", "Test replacement assumptions against device age and feature adoption."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0000320193&owner=exclude&action=getcompany&type=10-K",
    ),
    "AMZN": _focused_profile(
        business_model="A commerce, logistics, cloud-computing, advertising and subscription platform whose shared infrastructure supports multiple high-scale profit pools.",
        thesis="AWS, advertising and retail efficiency can expand operating cash generation as automation and network density improve the economics of the commerce base.",
        counter="AI infrastructure spending, retail capital intensity and price competition can absorb the profit pool before returns on new capacity are proven.",
        engines=["AWS and enterprise AI", "Advertising", "Retail productivity and third-party services"],
        kpis=["AWS growth and margin", "Advertising growth", "North America margin", "Capex and finance leases"],
        questions=["Does AWS growth earn an adequate return on AI infrastructure?", "How durable is retail margin improvement?", "Can advertising scale without weakening customer experience?"],
        moat=[("Scale", "Traffic, sellers and infrastructure reinforce unit economics."), ("AWS", "A broad cloud platform embeds enterprise workloads."), ("Logistics", "Dense fulfillment and delivery networks compress time and cost."), ("Demand data", "Commerce intent supports advertising and merchandising.")],
        catalysts=["AWS growth accelerates with stable margins.", "Retail fulfillment productivity improves.", "Advertising outgrows commerce volume.", "Capex growth moderates after capacity deployment."],
        risks=["AI capex outruns monetization.", "Retail competition forces reinvestment.", "Regulatory remedies alter marketplace economics.", "Cloud customers optimize spending."],
        monitoring=[("AWS", "Growth, backlog and margin"), ("Retail", "Units, delivery cost and margin"), ("Ads", "Growth and load"), ("Cash", "Capex, leases and FCF")],
        scenario=(.07, .12, .17, .08, .13, .17),
        dimensions=["Cloud", "Commerce", "Logistics", "Advertising", "Scale"],
        scores={"Amazon": [5, 5, 5, 5, 5], "Microsoft": [5, 3, 2, 3, 5], "Google": [4, 2, 2, 5, 5], "Walmart": [2, 5, 5, 3, 5]},
        diligence=["Reconcile AWS growth with infrastructure additions.", "Separate structural retail margin from temporary cost actions.", "Track lease-adjusted cash generation."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0001018724&owner=exclude&action=getcompany&type=10-K",
    ),
    "META": _focused_profile(
        business_model="A global social, messaging and advertising platform monetized through engagement, recommendation systems, business messaging and emerging devices.",
        thesis="AI-driven recommendation and advertising tools can compound engagement and advertiser returns while the scale of the core platform funds new products.",
        counter="Infrastructure intensity, regulation and unproven long-duration investments can reduce cash returns even if engagement and reported revenue remain strong.",
        engines=["AI-enhanced advertising", "Reels and messaging monetization", "Business messaging"],
        kpis=["Ad impressions and price", "Family daily active people", "Capex", "Reality Labs losses"],
        questions=["How much AI capex is required per unit of ad growth?", "Can messaging become a material profit pool?", "Does engagement remain resilient across younger users?"],
        moat=[("Social graph", "Identity and relationships support persistent engagement."), ("Recommendation", "Large interaction datasets improve content discovery."), ("Advertiser tools", "Measurement and automation lower campaign friction."), ("Scale", "Global reach funds infrastructure and product experimentation.")],
        catalysts=["Ad ranking lifts conversion and pricing.", "Messaging revenue becomes material.", "Infrastructure utilization improves.", "Reality Labs losses narrow."],
        risks=["Capex grows faster than monetization.", "Regulation limits targeting or acquisitions.", "New formats shift engagement away from monetizable surfaces.", "Long-duration hardware investment remains loss-making."],
        monitoring=[("Engagement", "Users, time and Reels mix"), ("Ads", "Impressions, price and conversion"), ("AI", "Capex and utilization"), ("Options", "Messaging and Reality Labs economics")],
        scenario=(.07, .13, .19, .32, .39, .44),
        dimensions=["Audience", "Data", "Advertising", "AI", "Messaging"],
        scores={"Meta": [5, 5, 5, 5, 5], "Alphabet": [5, 5, 5, 5, 3], "TikTok": [5, 4, 4, 4, 2], "Amazon": [4, 5, 5, 4, 2]},
        diligence=["Measure incremental ad returns against AI infrastructure cost.", "Separate engagement growth from monetization growth.", "Track regulatory constraints by region."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0001326801&owner=exclude&action=getcompany&type=10-K",
    ),
    "LITE": _focused_profile(
        business_model="An optical and photonic components supplier serving cloud, telecom, industrial lasers and sensing markets.",
        thesis="High-speed cloud interconnect and photonics demand can lift mix and utilization as AI clusters require more optical bandwidth.",
        counter="Customer concentration, technology transitions and volatile telecom demand can create sharp swings in utilization, margins and working capital.",
        engines=["Cloud optical transceivers", "Datacom photonics", "Industrial and sensing lasers"],
        kpis=["Cloud and networking revenue", "Gross margin", "Customer concentration", "Inventory"],
        questions=["How durable is AI-driven optical demand?", "Can manufacturing yields support target margins?", "Which customers account for the next capacity cycle?"],
        moat=[("Photonics IP", "Optical design and manufacturing expertise raise qualification barriers."), ("Customer qualification", "Components are validated inside long platform cycles."), ("Vertical capability", "Internal component expertise supports performance and supply."), ("Portfolio", "Cloud, telecom and industrial applications diversify demand.")],
        catalysts=["800G and 1.6T deployments accelerate.", "New capacity reaches target yields.", "Telecom demand normalizes.", "Mix lifts gross margin."],
        risks=["A major customer delays deployments.", "Yield or supply problems constrain shipments.", "Price erosion offsets volume growth.", "Acquisition integration raises costs."],
        monitoring=[("Cloud", "Transceiver demand and design wins"), ("Yields", "Gross margin and ramp costs"), ("Customers", "Concentration and timing"), ("Inventory", "Turns and channel health")],
        scenario=(.03, .13, .23, .06, .14, .21),
        dimensions=["Photonics", "Cloud access", "Manufacturing", "Portfolio", "Scale"],
        scores={"Lumentum": [5, 4, 4, 4, 3], "Coherent": [5, 5, 5, 5, 5], "Fabrinet": [3, 4, 5, 3, 4], "Applied Optoelectronics": [4, 4, 3, 3, 2]},
        diligence=["Identify program-level customer concentration.", "Separate shipment growth from pricing.", "Track yield and utilization through each ramp."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0001633978&owner=exclude&action=getcompany&type=10-K",
    ),
    "AMAT": _focused_profile(
        business_model="A semiconductor and display equipment company spanning deposition, materials engineering, process control and recurring services.",
        thesis="Rising device complexity and materials intensity can expand equipment content per wafer while services add recurring earnings through the installed base.",
        counter="Export controls, customer concentration and a cyclical spending slowdown can overwhelm structural content growth for extended periods.",
        engines=["Leading-edge logic and foundry", "Advanced packaging", "Installed-base services"],
        kpis=["Semiconductor systems revenue", "China mix", "Services growth", "Gross margin"],
        questions=["How much content growth survives lower wafer-fab spending?", "Can advanced packaging become a material profit pool?", "What is the normalized China exposure?"],
        moat=[("Materials engineering", "Process know-how supports critical manufacturing steps."), ("Installed base", "A large equipment base creates service and upgrade demand."), ("Customer integration", "Tools are qualified inside long production roadmaps."), ("R&D scale", "Broad investment spans multiple process inflections.")],
        catalysts=["Leading-edge fab spending rises.", "Advanced packaging revenue scales.", "Services outgrow systems.", "New products gain process share."],
        risks=["Export restrictions reduce accessible demand.", "Memory or foundry capex falls.", "Customers insource process capability.", "A competitor wins a key process step."],
        monitoring=[("WFE", "Customer capex and tool demand"), ("China", "Revenue mix and restrictions"), ("Services", "Installed-base growth"), ("Share", "Process wins and intensity")],
        scenario=(.01, .07, .13, .25, .29, .32),
        dimensions=["Deposition", "Services", "Packaging", "Process breadth", "Scale"],
        scores={"Applied Materials": [5, 5, 5, 5, 5], "Lam Research": [5, 5, 4, 4, 5], "KLA": [3, 5, 4, 4, 5], "Tokyo Electron": [5, 4, 4, 5, 5]},
        diligence=["Map revenue to customer capex cycles.", "Quantify export-control exposure by product.", "Test service durability in a downcycle."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0000006951&owner=exclude&action=getcompany&type=10-K",
    ),
    "TSM": _focused_profile(
        business_model="The leading dedicated semiconductor foundry, manufacturing advanced and specialty process nodes for global fabless and integrated-device customers.",
        thesis="Process leadership, scale and customer trust can sustain high utilization and attractive economics as advanced compute demand increases silicon complexity.",
        counter="The capital burden, geopolitical concentration and dependence on a small group of advanced-node customers create risks that accounting margins alone cannot capture.",
        engines=["Advanced-node wafers", "Advanced packaging", "High-performance computing"],
        kpis=["Advanced-node revenue mix", "Utilization", "Gross margin", "Capital expenditure"],
        questions=["Does leading-edge demand support the capital plan?", "How quickly can overseas fabs reach target economics?", "How concentrated is advanced-node demand?"],
        moat=[("Process leadership", "Yield and manufacturing learning compound across nodes."), ("Scale", "High volumes support R&D and supplier economics."), ("Neutrality", "A pure-play model reduces direct product competition with customers."), ("Ecosystem", "Design tools and IP are optimized around the manufacturing platform.")],
        catalysts=["Advanced-node utilization remains high.", "Packaging capacity expands.", "Overseas fabs qualify major customers.", "AI demand broadens beyond a few buyers."],
        risks=["Geopolitical disruption affects Taiwan operations.", "Overseas expansion dilutes margins.", "A customer shifts production or designs.", "Capital intensity rises faster than demand."],
        monitoring=[("Nodes", "3nm/2nm mix and yields"), ("Utilization", "Capacity and lead times"), ("Capex", "Build schedule and returns"), ("Geography", "Overseas ramp and policy")],
        scenario=(.06, .13, .20, .38, .46, .51),
        dimensions=["Process", "Scale", "Yield", "Packaging", "Trust"],
        scores={"TSMC": [5, 5, 5, 5, 5], "Samsung Foundry": [4, 5, 4, 4, 3], "Intel Foundry": [3, 4, 3, 4, 3], "UMC": [2, 3, 4, 2, 4]},
        diligence=["Stress-test capacity against customer concentration.", "Separate overseas policy support from structural cost.", "Track advanced packaging as a bottleneck and profit pool."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0001046179&owner=exclude&action=getcompany&type=20-F",
    ),
    "ASML": _focused_profile(
        business_model="A lithography systems and services company whose EUV, DUV and installed-base offerings are critical to advanced semiconductor manufacturing.",
        thesis="EUV technology leadership and a growing installed base can sustain pricing power and recurring service economics as chip complexity increases.",
        counter="Customer concentration, export controls and highly lumpy system acceptances can make demand and cash conversion volatile despite a uniquely strong competitive position.",
        engines=["High-NA EUV adoption", "EUV system growth", "Installed-base management"],
        kpis=["EUV shipments and ASP", "Bookings", "Gross margin", "China sales mix"],
        questions=["How quickly does High-NA move into volume production?", "What level of China demand is structurally accessible?", "Can suppliers scale without constraining shipments?"],
        moat=[("EUV monopoly", "Decades of engineering created a unique production platform."), ("Supplier network", "Critical optics and components are co-developed over long cycles."), ("Installed base", "Service and upgrades deepen customer integration."), ("Roadmap", "Customers coordinate leading-edge process plans with ASML systems.")],
        catalysts=["High-NA adoption broadens.", "Logic and memory spending recover.", "Installed-base revenue compounds.", "Supply constraints ease."],
        risks=["Export restrictions reduce shipments.", "Customers delay fab ramps.", "High-NA economics disappoint.", "Supplier bottlenecks disrupt output."],
        monitoring=[("Bookings", "Order timing and cancellation risk"), ("EUV", "Shipments, ASP and acceptance"), ("China", "Mix and restrictions"), ("Services", "Installed-base growth")],
        scenario=(.04, .11, .18, .29, .35, .39),
        dimensions=["EUV", "Roadmap", "Installed base", "Suppliers", "Scale"],
        scores={"ASML": [5, 5, 5, 5, 5], "Nikon": [2, 2, 3, 3, 3], "Canon": [2, 3, 3, 3, 3], "Applied Materials": [1, 4, 5, 5, 5]},
        diligence=["Track bookings by customer and planned acceptance.", "Quantify export-control sensitivity.", "Test High-NA returns across customer roadmaps."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0000937966&owner=exclude&action=getcompany&type=20-F",
    ),
    "AMD": _focused_profile(
        business_model="A fabless semiconductor company spanning data-center CPUs and GPUs, client processors, gaming and embedded products.",
        thesis="Share gains in server CPUs and expanding accelerator adoption can lift mix and operating leverage as AMD offers a broader data-center compute portfolio.",
        counter="Software ecosystem gaps, intense NVIDIA and Intel competition and acquisition-related costs can limit returns even when product performance is strong.",
        engines=["EPYC server CPUs", "Instinct accelerators", "Client and embedded recovery"],
        kpis=["Data-center revenue", "Gross margin", "Accelerator revenue", "Client and embedded trends"],
        questions=["Can ROCm reduce the software adoption barrier?", "How durable are server CPU share gains?", "Does accelerator growth improve or dilute margin?"],
        moat=[("Chiplets", "Modular design supports flexible performance and cost."), ("CPU roadmap", "Competitive server and client products broaden customer access."), ("Foundry access", "Leading-node manufacturing supports product cadence."), ("Portfolio", "CPU, GPU and adaptive computing span heterogeneous workloads.")],
        catalysts=["Accelerator revenue and customer count expand.", "Server CPU share continues rising.", "Client and embedded demand recover.", "Software adoption lowers deployment friction."],
        risks=["NVIDIA retains software and platform dominance.", "Intel pricing slows CPU share gains.", "Supply or packaging limits accelerator ramps.", "Acquisition amortization obscures core returns."],
        monitoring=[("Data center", "CPU and GPU revenue"), ("Software", "ROCm deployments"), ("Margins", "Mix and operating leverage"), ("Roadmap", "Launch timing and supply")],
        scenario=(.07, .16, .25, .10, .17, .23),
        dimensions=["CPU", "GPU", "Software", "Chiplets", "Scale"],
        scores={"AMD": [5, 4, 3, 5, 4], "NVIDIA": [3, 5, 5, 4, 5], "Intel": [5, 3, 4, 4, 5], "Broadcom": [2, 4, 3, 4, 5]},
        diligence=["Separate accelerator pipeline from recognized revenue.", "Track software deployments, not only downloads.", "Reconcile share gains with gross-margin progression."],
        source_url="https://www.sec.gov/edgar/browse/?CIK=0000002488&owner=exclude&action=getcompany&type=10-K",
    ),
})


def target_price_snapshot(ticker: str) -> dict[str, object]:
    return TARGET_PRICE_SNAPSHOTS.get(ticker, {"as_of": "", "source_url": "", "street": [], "house": {}, "basis": ""})


def market_share_snapshot(ticker: str) -> dict[str, object]:
    return MARKET_SHARE_SNAPSHOTS.get(ticker, {"title": "", "period": "", "values": {}, "source": "", "source_url": "", "note": ""})
